class PredefinedPresets {
    const ATT_60_ZERKER_94: Presetable = {
        name: "60Att. Zerker",
        inventory: [
            { name: "DRAGON_DAGGER_P_PLUS_PLUS_" },
            { name: "SHARK" },
            { name: "SUPER_ATTACK_4_" },
            { name: "SUPER_STRENGTH_4_" },
            { name: "COOKED_KARAMBWAN" },
            { name: "SHARK" },
            { name: "SUPER_RESTORE_4_" },
            { name: "SARADOMIN_BREW_4_" },
            { name: "COOKED_KARAMBWAN" },
            { name: "SHARK" },
            { name: "SUPER_RESTORE_4_" },
            { name: "SARADOMIN_BREW_4_" },
            { name: "COOKED_KARAMBWAN" },
            { name: "SHARK" },
            { name: "SHARK" },
            { name: "SHARK" },
            { name: "COOKED_KARAMBWAN" },
            { name: "SHARK" },
            { name: "SHARK" },
            { name: "SHARK" },
            { name: "COOKED_KARAMBWAN" },
            { name: "SHARK" },
            { name: "SHARK" },
            { name: "RING_OF_RECOIL" },
            { name: "DEATH_RUNE", quantity: 1000 },
            { name: "EARTH_RUNE", quantity: 1000 },
            { name: "ASTRAL_RUNE", quantity: 1000 },
            { name: "SHARK" },
        ],
        equipment: [
            { name: "WARRIOR_HELM" },
            { name: "STRENGTH_CAPE_T_" },
            { name: "DRAGON_SCIMITAR" },
            { name: "AMULET_OF_GLORY" },
            { name: "RUNE_PLATEBODY" },
            { name: "RUNE_DEFENDER" },
            { name: "RUNE_PLATELEGS" },
            { name: "BARROWS_GLOVES" },
            { name: "RUNE_BOOTS" },
            { name: "RING_OF_RECOIL" },
            null,
        ],
        stats: {
            attack: 60,
            defense: 45,
            strength: 99,
            hitpoints: 95,
            ranged: 99,
            prayer: 52,
            magic: 94
        },
        spellbook: MagicSpellbook.LUNAR,
        isMembers: true
    }

    const ATT_70_ZERKER_97: Presetable = {
        name: "70Att. Zerker",
        inventory: [
            { name: "DRAGON_DAGGER_P_PLUS_PLUS_" },
            { name: "SHARK" },
            { name: "SUPER_ATTACK_4_" },
            { name: "SUPER_STRENGTH_4_" },
            { name: "COOKED_KARAMBWAN" },
            { name: "SHARK" },
            { name: "SUPER_RESTORE_4_" },
            { name: "SARADOMIN_BREW_4_" },
            { name: "COOKED_KARAMBWAN" },
            { name: "SHARK" },
            { name: "SUPER_RESTORE_4_" },
            { name: "SARADOMIN_BREW_4_" },
            { name: "COOKED_KARAMBWAN" },
            { name: "SHARK" },
            { name: "SHARK" },
            { name: "SHARK" },
            { name: "COOKED_KARAMBWAN" },
            { name: "SHARK" },
            { name: "SHARK" },
            { name: "SHARK" },
            { name: "COOKED_KARAMBWAN" },
            { name: "SHARK" },
            { name: "SHARK" },
            { name: "RING_OF_RECOIL" },
            { name: "DEATH_RUNE", quantity: 1000 },
            { name: "EARTH_RUNE", quantity: 1000 },
            { name: "ASTRAL_RUNE", quantity: 1000 },
            { name: "SHARK" },
        ],
        equipment: [
            { name: "WARRIOR_HELM" },
            { name: "STRENGTH_CAPE_T_" },
            { name: "ABYSSAL_WHIP" },
            { name: "AMULET_OF_GLORY" },
            { name: "RUNE_PLATEBODY" },
            { name: "RUNE_DEFENDER" },
            { name: "RUNE_PLATELEGS" },
            { name: "BARROWS_GLOVES" },
            { name: "RUNE_BOOTS" },
            { name: "RING_OF_RECOIL" },
            null,
        ],
        stats: {
            attack: 70,
            defense: 45,
            strength: 99,
            hitpoints: 95,
            ranged: 99,
            prayer: 52,
            magic: 94
        },
        spellbook: MagicSpellbook.LUNAR,
        isMembers: true
    }

    const DDS_PURE_M_73: Presetable = new Presetable("DDS Pure (M)", [
        new Item(DRAGON_DAGGER_P_PLUS_PLUS_), new Item(SHARK), new Item(SHARK), new Item(SUPER_STRENGTH_4_),
        new Item(COOKED_KARAMBWAN), new Item(SHARK), new Item(SUPER_RESTORE_4_), new Item(SUPER_ATTACK_4_),
        new Item(COOKED_KARAMBWAN), new Item(SHARK), new Item(SARADOMIN_BREW_4_), new Item(SARADOMIN_BREW_4_),
        new Item(COOKED_KARAMBWAN), new Item(SHARK), new Item(SHARK), new Item(SHARK),
        new Item(COOKED_KARAMBWAN), new Item(SHARK), new Item(SHARK), new Item(SHARK),
        new Item(COOKED_KARAMBWAN), new Item(SHARK), new Item(SHARK), new Item(SHARK),
        new Item(COOKED_KARAMBWAN), new Item(SHARK), new Item(RING_OF_RECOIL), new Item(SHARK),
    ],
        [
            new Item(IRON_FULL_HELM),
            new Item(OBSIDIAN_CAPE),
            new Item(DRAGON_SCIMITAR),
            new Item(AMULET_OF_GLORY),
            new Item(IRON_PLATEBODY),
            new Item(BOOK_OF_DARKNESS),
            new Item(BLACK_DHIDE_CHAPS),
            new Item(MITHRIL_GLOVES),
            new Item(CLIMBING_BOOTS),
            new Item(RING_OF_RECOIL),
            null,
        ],
        [60, 1, 99, 85, 1, 1, 1],
        MagicSpellbook.NORMAL,
        true
    );

    const DDS_PURE_R_73: Presetable = new Presetable("DDS Pure (R)", [
        new Item(RUNE_CROSSBOW), new Item(DRAGON_BOLTS_E_, 75), new Item(RANGING_POTION_4_), new Item(SUPER_STRENGTH_4_),
        new Item(COOKED_KARAMBWAN), new Item(DRAGON_DAGGER_P_PLUS_PLUS_), new Item(SUPER_RESTORE_4_), new Item(SUPER_ATTACK_4_),
        new Item(COOKED_KARAMBWAN), new Item(SHARK), new Item(SARADOMIN_BREW_4_), new Item(SARADOMIN_BREW_4_),
        new Item(COOKED_KARAMBWAN), new Item(SHARK), new Item(SHARK), new Item(SHARK),
        new Item(COOKED_KARAMBWAN), new Item(SHARK), new Item(SHARK), new Item(SHARK),
        new Item(COOKED_KARAMBWAN), new Item(SHARK), new Item(SHARK), new Item(SHARK),
        new Item(COOKED_KARAMBWAN), new Item(SHARK), new Item(RING_OF_RECOIL), new Item(SHARK),
    ],
        [
            new Item(COIF),
            new Item(AVAS_ACCUMULATOR),
            new Item(MAGIC_SHORTBOW),
            new Item(AMULET_OF_GLORY),
            new Item(LEATHER_BODY),
            null,
            new Item(BLACK_DHIDE_CHAPS),
            new Item(MITHRIL_GLOVES),
            new Item(CLIMBING_BOOTS),
            new Item(RING_OF_RECOIL),
            new Item(RUNE_ARROW, 75),
        ],
        [50, 1, 99, 85, 99, 1, 1],
        MagicSpellbook.NORMAL,
        true
    );

    const MAIN_HYBRID_126: Presetable = new Presetable("Main Hybrid", [
        new Item(RUNE_PLATEBODY), new Item(ABYSSAL_WHIP), new Item(BLACK_DHIDE_BODY), new Item(SARADOMIN_BREW_4_),
        new Item(RUNE_PLATELEGS), new Item(RUNE_DEFENDER), new Item(DRAGON_DAGGER_P_PLUS_PLUS_), new Item(SARADOMIN_BREW_4_),
        new Item(COOKED_KARAMBWAN), new Item(COOKED_KARAMBWAN), new Item(COOKED_KARAMBWAN), new Item(SUPER_RESTORE_4_),
        new Item(SHARK), new Item(SHARK), new Item(SHARK), new Item(SUPER_RESTORE_4_),
        new Item(SHARK), new Item(SHARK), new Item(SHARK), new Item(SUPER_ATTACK_4_),
        new Item(SHARK), new Item(SHARK), new Item(SHARK), new Item(SUPER_STRENGTH_4_),
        new Item(SHARK), new Item(DEATH_RUNE, 4000), new Item(WATER_RUNE, 6000), new Item(BLOOD_RUNE, 2000),
    ],
        [
            new Item(HELM_OF_NEITIZNOT),
            new Item(SARADOMIN_CAPE),
            new Item(ANCIENT_STAFF),
            new Item(AMULET_OF_GLORY),
            new Item(MYSTIC_ROBE_TOP),
            new Item(UNHOLY_BOOK),
            new Item(MYSTIC_ROBE_BOTTOM),
            new Item(BARROWS_GLOVES),
            new Item(CLIMBING_BOOTS),
            new Item(RING_OF_RECOIL),
            null,
        ],
        [99, 99, 99, 99, 99, 99, 99],
        MagicSpellbook.ANCIENT,
        true
    );

    const MAIN_RUNE_126: Presetable = new Presetable("Main Rune", [
        new Item(SUPER_STRENGTH_4_), new Item(SARADOMIN_BREW_4_), new Item(SUPER_RESTORE_4_), new Item(SUPER_RESTORE_4_),
        new Item(SUPER_ATTACK_4_), new Item(ASTRAL_RUNE, 1000), new Item(EARTH_RUNE, 1000), new Item(DEATH_RUNE, 1000),
        new Item(DRAGON_DAGGER_P_PLUS_PLUS_), new Item(COOKED_KARAMBWAN), new Item(COOKED_KARAMBWAN), new Item(COOKED_KARAMBWAN),
        new Item(COOKED_KARAMBWAN), new Item(COOKED_KARAMBWAN), new Item(COOKED_KARAMBWAN), new Item(COOKED_KARAMBWAN),
        new Item(SHARK), new Item(SHARK), new Item(SHARK), new Item(SHARK),
        new Item(SHARK), new Item(SHARK), new Item(SHARK), new Item(SHARK),
        new Item(SHARK), new Item(SHARK), new Item(RING_OF_RECOIL), new Item(SHARK),
    ],
        [
            new Item(HELM_OF_NEITIZNOT),
            new Item(OBSIDIAN_CAPE),
            new Item(ABYSSAL_WHIP),
            new Item(AMULET_OF_GLORY),
            new Item(RUNE_PLATEBODY),
            new Item(RUNE_DEFENDER),
            new Item(RUNE_PLATELEGS),
            new Item(BARROWS_GLOVES),
            new Item(DRAGON_BOOTS),
            new Item(RING_OF_RECOIL),
            null,
        ],
        [99, 99, 99, 99, 99, 99, 99],
        MagicSpellbook.LUNAR,
        true
    );

    const NH_PURE_83 = new Presetable("NH Pure",
        [
            new Item(RUNE_CROSSBOW), new Item(BLACK_DHIDE_CHAPS), new Item(RANGING_POTION_4_), new Item(SUPER_STRENGTH_4_),
            new Item(AVAS_ACCUMULATOR), new Item(DRAGON_DAGGER_P_PLUS_PLUS_), new Item(SUPER_RESTORE_4_), new Item(SUPER_ATTACK_4_),
            new Item(DRAGON_BOLTS_E_, 75), new Item(BOOK_OF_WAR), new Item(SUPER_RESTORE_4_), new Item(SARADOMIN_BREW_4_),
            new Item(COOKED_KARAMBWAN), new Item(SHARK), new Item(SHARK), new Item(SARADOMIN_BREW_4_),
            new Item(COOKED_KARAMBWAN), new Item(SHARK), new Item(SHARK), new Item(SHARK),
            new Item(COOKED_KARAMBWAN), new Item(SHARK), new Item(SHARK), new Item(SHARK),
            new Item(WATER_RUNE, 1000), new Item(BLOOD_RUNE, 1000), new Item(DEATH_RUNE, 1000), new Item(SHARK),
        ],
        [
            new Item(GREY_HAT),
            new Item(ZAMORAK_CAPE),
            new Item(MAGIC_SHORTBOW),
            new Item(AMULET_OF_GLORY),
            new Item(ZAMORAK_ROBE),
            null,
            new Item(ZAMORAK_ROBE_3),
            new Item(MITHRIL_GLOVES),
            new Item(CLIMBING_BOOTS),
            new Item(RING_OF_RECOIL),
            new Item(RUNE_ARROW, 175),
        ],
        /* atk, def, str, hp, range, pray, mage */
        [60, 1, 85, 99, 99, 1, 99],
        MagicSpellbook.ANCIENT,
        true
    );

    const OBBY_MAULER_57 = new Presetable("Obby Mauler",
        [
            new Item(SUPER_STRENGTH_4_), new Item(RANGING_POTION_4_), new Item(SUPER_RESTORE_4_), new Item(RING_OF_RECOIL),
            new Item(COOKED_KARAMBWAN), new Item(COOKED_KARAMBWAN), new Item(COOKED_KARAMBWAN), new Item(COOKED_KARAMBWAN),
            new Item(COOKED_KARAMBWAN), new Item(COOKED_KARAMBWAN), new Item(COOKED_KARAMBWAN), new Item(COOKED_KARAMBWAN),
            new Item(TZHAAR_KET_OM), new Item(SHARK), new Item(SHARK), new Item(SHARK),
            new Item(SHARK), new Item(SHARK), new Item(SHARK), new Item(SHARK),
            new Item(SHARK), new Item(SHARK), new Item(SHARK), new Item(SHARK),
            new Item(SHARK), new Item(SHARK), new Item(SHARK), new Item(SHARK),
        ],
        [
            new Item(IRON_FULL_HELM),
            new Item(OBSIDIAN_CAPE),
            new Item(RUNE_KNIFE, 250),
            new Item(AMULET_OF_GLORY),
            new Item(IRON_PLATEBODY),
            new Item(UNHOLY_BOOK),
            new Item(BLACK_DHIDE_CHAPS),
            new Item(MITHRIL_GLOVES),
            new Item(CLIMBING_BOOTS),
            new Item(RING_OF_RECOIL)
        ],
        /* atk, def, str, hp, range, pray, mage */
        [1, 1, 99, 80, 60, 31, 1],
        MagicSpellbook.NORMAL,
        true
    );

    const MAIN_TRIBRID_126: Presetable = new Presetable("Main Tribrid",
        [
            new Item(AVAS_ACCUMULATOR), new Item(BLACK_DHIDE_BODY), new Item(ABYSSAL_WHIP), new Item(SARADOMIN_BREW_4_),
            new Item(RUNE_CROSSBOW), new Item(RUNE_PLATELEGS), new Item(RUNE_DEFENDER), new Item(SARADOMIN_BREW_4_),
            new Item(COOKED_KARAMBWAN), new Item(COOKED_KARAMBWAN), new Item(DRAGON_DAGGER_P_PLUS_PLUS_), new Item(SUPER_RESTORE_4_),
            new Item(SHARK), new Item(SHARK), new Item(SHARK), new Item(SUPER_RESTORE_4_),
            new Item(SHARK), new Item(SHARK), new Item(SHARK), new Item(SUPER_STRENGTH_4_),
            new Item(SHARK), new Item(SHARK), new Item(SHARK), new Item(SUPER_ATTACK_4_),
            new Item(WATER_RUNE, 6000), new Item(BLOOD_RUNE, 2000), new Item(DEATH_RUNE, 4000), new Item(RANGING_POTION_4_),
        ],
        [
            new Item(HELM_OF_NEITIZNOT),
            new Item(SARADOMIN_CAPE),
            new Item(ANCIENT_STAFF),
            new Item(AMULET_OF_GLORY),
            new Item(MYSTIC_ROBE_TOP),
            new Item(SPIRIT_SHIELD),
            new Item(MYSTIC_ROBE_BOTTOM),
            new Item(BARROWS_GLOVES),
            new Item(CLIMBING_BOOTS),
            new Item(RING_OF_RECOIL),
            new Item(DRAGON_BOLTS_E_, 500),
        ],
        /* atk, def, str, hp, range, pray, mage */
        [99, 99, 99, 99, 99, 99, 99],
        MagicSpellbook.ANCIENT,
        true
    );
}